services:
  config1:
    image: mongo:8.0
    container_name: ddb-config1
    command: ["mongod", "--configsvr", "--replSet", "cfgRS", "--port", "27019", "--bind_ip_all"]
    volumes:
      - config1-data:/data/db
      - ./scripts:/scripts:ro
    networks: [ddbnet]

  config2:
    image: mongo:8.0
    container_name: ddb-config2
    command: ["mongod", "--configsvr", "--replSet", "cfgRS", "--port", "27019", "--bind_ip_all"]
    volumes:
      - config2-data:/data/db
      - ./scripts:/scripts:ro
    networks: [ddbnet]

  config3:
    image: mongo:8.0
    container_name: ddb-config3
    command: ["mongod", "--configsvr", "--replSet", "cfgRS", "--port", "27019", "--bind_ip_all"]
    volumes:
      - config3-data:/data/db
      - ./scripts:/scripts:ro
    networks: [ddbnet]

  shard-egypt:
    image: mongo:8.0
    container_name: ddb-shard-egypt
    command: ["mongod", "--shardsvr", "--replSet", "rsEgypt", "--port", "27018", "--bind_ip_all"]
    volumes:
      - shard-egypt-data:/data/db
      - ./scripts:/scripts:ro
    networks: [ddbnet]

  shard-europe:
    image: mongo:8.0
    container_name: ddb-shard-europe
    command: ["mongod", "--shardsvr", "--replSet", "rsEurope", "--port", "27018", "--bind_ip_all"]
    volumes:
      - shard-europe-data:/data/db
      - ./scripts:/scripts:ro
    networks: [ddbnet]

  shard-usa:
    image: mongo:8.0
    container_name: ddb-shard-usa
    command: ["mongod", "--shardsvr", "--replSet", "rsUSA", "--port", "27018", "--bind_ip_all"]
    volumes:
      - shard-usa-data:/data/db
      - ./scripts:/scripts:ro
    networks: [ddbnet]

  mongos:
    image: mongo:8.0
    container_name: ddb-mongos
    depends_on:
      - config1
      - config2
      - config3
      - shard-egypt
      - shard-europe
      - shard-usa
    command:
      [
        "mongos",
        "--configdb",
        "cfgRS/config1:27019,config2:27019,config3:27019",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    ports:
      - "27017:27017"
    volumes:
      - ./scripts:/scripts:ro
    networks: [ddbnet]

networks:
  ddbnet:
    driver: bridge

volumes:
  config1-data:
  config2-data:
  config3-data:
  shard-egypt-data:
  shard-europe-data:
  shard-usa-data:
